---
- name: Install AAP Operator and create a project
  hosts: localhost
  gather_facts: false
  collections:
    - kubernetes.core
    - awx.awx
    - ansible.eda

  vars:
    namespace: aap
    project_name: "cell-tower"
    scm_url: "https://github.com/tolarewaju3/self-healing-config-drift.git"
    workflow_name: "cell-tower-remediation-workflow"

  tasks:
    - name: Create namespace for AAP
      k8s:
        api_version: v1
        kind: Namespace
        name: "{{ namespace }}"
        state: present

    - name: Create OperatorGroup
      k8s:
        api_version: operators.coreos.com/v1
        kind: OperatorGroup
        namespace: "{{ namespace }}"
        name: aap-operator-group
        definition:
          apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: aap-operator-group
          spec:
            targetNamespaces:
              - "{{ namespace }}"

    - name: Create Subscription for AAP Operator
      k8s:
        api_version: operators.coreos.com/v1alpha1
        kind: Subscription
        namespace: "{{ namespace }}"
        name: ansible-automation-platform-operator
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: ansible-automation-platform-operator
          spec:
            channel: stable-2.5
            name: ansible-automation-platform-operator
            source: redhat-operators
            sourceNamespace: openshift-marketplace

    - name: Wait for AAP operator to be ready
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: aap
        label_selectors:
          - app.kubernetes.io/name=ansible-automation-platform-operator
        wait: yes

    - name: Create AnsibleAutomationPlatform custom resource
      k8s:
        state: present
        definition:
          apiVersion: aap.ansible.com/v1alpha1
          kind: AnsibleAutomationPlatform
          metadata:
            name: aap
            namespace: "{{ namespace }}"
          spec:
            route_tls_termination_mechanism: Edge
            no_log: true
            redis_mode: standalone
            api:
              log_level: INFO
              replicas: 1
            database:
              postgres_data_volume_init: false

    - name: Wait for AAP route to deploy
      kubernetes.core.k8s_info:
        kind: Route
        namespace: aap
        name: aap
        wait: yes
      register: aap_route

    - name: Wait for ansible controller route to deploy
      kubernetes.core.k8s_info:
        kind: Route
        namespace: aap
        name: aap-controller
        wait: yes
      register: controller_route

    - name: Wait for EDA route to deploy
      kubernetes.core.k8s_info:
        kind: Route
        namespace: aap
        name: aap-eda
        wait: yes
      register: eda_route

    - name: Set AAP hostname
      set_fact:
        aap_hostname: "https://{{ aap_route.resources[0].spec.host }}"

    - name: Set controller hostname
      set_fact:
        controller_hostname: "https://{{ controller_route.resources[0].spec.host }}"

    - name: Set EDA controller hostname
      set_fact:
        eda_hostname: "https://{{ eda_route.resources[0].spec.host }}"

    - name: Get AAP admin password from secret
      k8s_info:
        api_version: v1
        kind: Secret
        namespace: "{{ namespace }}"
        name: aap-admin-password
      register: aap_secret

    - name: Get EDA admin password from secret
      k8s_info:
        api_version: v1
        kind: Secret
        namespace: "{{ namespace }}"
        name: aap-eda-admin-password
      register: eda_secret

    - name: Get controller admin password from secret
      k8s_info:
        api_version: v1
        kind: Secret
        namespace: "{{ namespace }}"
        name: aap-controller-admin-password
      register: controller_secret

    - name: Debug full secret structure
      debug:
        var: controller_secret

    - name: Debug full hostname
      debug:
        var: controller_hostname

    - name: Set AAP password
      set_fact:
        aap_password: "{{ aap_secret.resources[0].data.password | b64decode }}"

    - name: Set EDA password
      set_fact:
        eda_password: "{{ eda_secret.resources[0].data.password | b64decode }}"

    - name: Set controller password
      set_fact:
        controller_password: "{{ controller_secret.resources[0].data.password | b64decode }}"

    - name: Create project in AAP
      awx.awx.project:
        controller_host: "{{ controller_hostname }}"
        controller_username: "admin"
        controller_password: "{{ controller_password }}"
        default_environment: "Default execution environment"
        validate_certs: false
        name: "{{ project_name }}"
        organization: Default
        scm_type: git
        scm_url: "{{ scm_url }}"
        scm_branch: master
        state: present

    - name: Create Supabase custom credential type
      awx.awx.credential_type:
        controller_host: "{{ controller_hostname }}"
        controller_username: "admin"
        controller_password: "{{ controller_password }}"
        validate_certs: false
        name: "supabase_key"
        kind: "cloud"
        description: "Credential type for Supabase access"
        inputs:
          fields:
            - id: supabase_anon_key
              type: string
              label: Supabase Anon Key
              secret: true
          required:
            - supabase_anon_key
        injectors:
          env:
            SUPABASE_ANON_KEY: "{{ supabase_anon_key }}"
        state: present

    - name: Create Supabase credential
      awx.awx.credential:
        controller_host: "{{ controller_hostname }}"
        controller_username: "admin"
        controller_password: "{{ controller_password }}"
        validate_certs: false
        name: "supabase"
        description: "Credential for Supabase access"
        credential_type: "supabase_key"
        organization: Default
        inputs:
          supabase_anon_key: "{{ supabase_anon_key }}"
        state: present

    - name: Create Servienow custom credential type
      awx.awx.credential_type:
        controller_host: "{{ controller_hostname }}"
        controller_username: "admin"
        controller_password: "{{ controller_password }}"
        validate_certs: false
        name: "servicenow_key"
        kind: "cloud"
        description: "Credential type for ServiceNow access"
        inputs:
          fields:
            - id: servicenow_host
              type: string
              label: ServiceNow Host
              secret: true
            - id: servicenow_username
              type: string
              label: ServiceNow Username
              secret: true
            - id: servicenow_password
              type: string
              label: ServiceNow Password
              secret: true
          required:
            - servicenow_host
            - servicenow_username
            - servicenow_password
        injectors:
          env:
            SN_HOST: "{{ servicenow_host }}"
            SN_USERNAME: "{{ servicenow_username }}"
            SN_PASSWORD: "{{ servicenow_password }}"
        state: present

    - name: Create Servicenow credential
      awx.awx.credential:
        controller_host: "{{ controller_hostname }}"
        controller_username: "admin"
        controller_password: "{{ controller_password }}"
        validate_certs: false
        name: "servicenow"
        description: "Credential for ServiceNow access"
        credential_type: "servicenow_key"
        organization: Default
        inputs:
          servicenow_host: "{{ servicenow_host }}"
          servicenow_username: "{{ servicenow_username }}"
          servicenow_password: "{{ servicenow_password }}"
        state: present

    - name: Create OpenShift Token Credential
      awx.awx.credential:
        controller_host: "{{ controller_hostname }}"
        controller_username: "admin"
        controller_password: "{{ controller_password }}"
        validate_certs: false
        name: "OpenShift Token Credential"
        organization: Default
        credential_type: "OpenShift or Kubernetes API Bearer Token"
        inputs:
          host: "{{ ocp_api_host }}"
          bearer_token: "{{ ocp_bearer_token }}"
      register: result

    - name: Create AAP Controller Credential
      awx.awx.credential:
        controller_host: "{{ controller_hostname }}"
        controller_username: "admin"
        controller_password: "{{ controller_password }}"
        validate_certs: false
        name: "AAP Controller Credential"
        organization: Default
        credential_type: "Red Hat Ansible Automation Platform"
        inputs:
          host: "{{ controller_hostname }}"
          username: "admin"
          password: "{{ controller_password }}"
      register: result

    - name: Create AAP Credential
      awx.awx.credential:
        controller_host: "{{ controller_hostname }}"
        controller_username: "admin"
        controller_password: "{{ controller_password }}"
        validate_certs: false
        name: "AAP Admin Credential"
        organization: Default
        credential_type: "Red Hat Ansible Automation Platform"
        inputs:
          host: "{{ aap_hostname }}"
          username: admin
          password: "{{ aap_password }}"
      register: result

    - name: Create Job Template for detect-drift
      awx.awx.job_template:
        controller_host: "{{ controller_hostname }}"
        controller_username: "admin"
        controller_password: "{{ controller_password }}"
        validate_certs: false
        name: "detect-drift"
        job_type: "run"
        project: "cell-tower"
        inventory: "Demo Inventory"
        playbook: "playbooks/detect-drift.yml"
        credentials: 
          - "AAP Controller Credential"
          - "supabase"
        execution_environment: "Default execution environment"
        ask_job_type_on_launch: true
        ask_variables_on_launch: true

    - name: Create Job Template for setup-cell-tower
      awx.awx.job_template:
        controller_host: "{{ controller_hostname }}"
        controller_username: "admin"
        controller_password: "{{ controller_password }}"
        validate_certs: false
        name: "setup-cell-tower"
        job_type: "run"
        project: "cell-tower"
        inventory: "Demo Inventory"
        playbook: "playbooks/setup-cell-tower.yml"
        credentials: 
          - "OpenShift Token Credential"
          - "supabase"
          - "servicenow"
        execution_environment: "Default execution environment"
        ask_job_type_on_launch: true
        ask_variables_on_launch: true

    - name: Create Job Template for create-service-now-incident
      awx.awx.job_template:
        controller_host: "{{ controller_hostname }}"
        controller_username: "admin"
        controller_password: "{{ controller_password }}"
        validate_certs: false
        name: "create-incident"
        job_type: "run"
        project: "cell-tower"
        inventory: "Demo Inventory"
        playbook: "playbooks/create-servicenow-incident.yml"
        credentials: 
          - "supabase"
          - "servicenow"
          - "AAP Admin Credential"
        execution_environment: "Default execution environment"
        ask_variables_on_launch: true

    - name: Create Workflow Template for cell tower remediation
      block:
      - name: Create Workflow Template
        awx.awx.workflow_job_template:
          controller_host: "{{ controller_hostname }}"
          controller_username: "admin"
          controller_password: "{{ controller_password }}"
          validate_certs: false
          name: "{{ workflow_name }}"
          description: "Creates a ServiceNow incident and then remediates the cell tower"
          organization: Default
          ask_variables_on_launch: true
          state: present

      - name: Add fix-cell-tower node to workflow
        awx.awx.workflow_job_template_node:
          controller_host: "{{ controller_hostname }}"
          controller_username: "admin"
          controller_password: "{{ controller_password }}"
          validate_certs: false
          identifier: "Fix Cell Tower"
          job_type: "run"
          workflow_job_template: "{{ workflow_name }}"
          unified_job_template: "setup-cell-tower"
          organization: Default
          state: present

      - name: Create approval node
        awx.awx.workflow_job_template_node:
          controller_host: "{{ controller_hostname }}"
          controller_username: "admin"
          controller_password: "{{ controller_password }}"
          validate_certs: false
          identifier: "Approve Remediation"
          workflow_job_template: "{{ workflow_name }}"
          approval_node:
            description: "Do this?"
            name: "approve-remediation"
            timeout: 3600
          organization: Default
          state: present

      - name: Link approval node to fix-cell-tower
        awx.awx.workflow_job_template_node:
          controller_host: "{{ controller_hostname }}"
          controller_username: "admin"
          controller_password: "{{ controller_password }}"
          validate_certs: false
          identifier: "Approve Remediation"
          workflow_job_template: "{{ workflow_name }}"
          success_nodes:
            - "Fix Cell Tower"
          organization: Default
          state: present

      - name: Add create-incident node to workflow
        awx.awx.workflow_job_template_node:
          controller_host: "{{ controller_hostname }}"
          controller_username: "admin"
          controller_password: "{{ controller_password }}"
          validate_certs: false
          identifier: "Create ServiceNow Ticket"
          workflow_job_template: "{{ workflow_name }}"
          unified_job_template: "create-incident"
          extra_data:
            config_drift: true
          always_nodes:
            - "Approve Remediation"
          organization: Default
          state: present

      - name: Add create-incident node to workflow
        awx.awx.workflow_job_template_node:
          controller_host: "{{ controller_hostname }}"
          controller_username: "admin"
          controller_password: "{{ controller_password }}"
          validate_certs: false
          identifier: "Create Ticket"
          workflow_job_template: "{{ workflow_name }}"
          unified_job_template: "create-incident"
          organization: Default
          state: present

      - name: Add detect-drift node to workflow
        awx.awx.workflow_job_template_node:
          controller_host: "{{ controller_hostname }}"
          controller_username: "admin"
          controller_password: "{{ controller_password }}"
          validate_certs: false
          identifier: "Drift Detected?"
          workflow_job_template: "{{ workflow_name }}"
          unified_job_template: "detect-drift"
          success_nodes:
            - "Create ServiceNow Ticket"
          failure_nodes:
            - "Create Ticket"
          organization: Default
          state: present

      - name: Add check-cell-tower node to workflow
        awx.awx.workflow_job_template_node:
          controller_host: "{{ controller_hostname }}"
          controller_username: "admin"
          controller_password: "{{ controller_password }}"
          validate_certs: false
          identifier: "Check Tower"
          job_type: "check"
          workflow_job_template: "{{ workflow_name }}"
          unified_job_template: "setup-cell-tower"
          success_nodes:
            - "Drift Detected?"
          organization: Default
          state: present

    - name: Create an EDA Credential
      ansible.eda.credential:
        controller_host: "{{ eda_hostname }}"
        controller_username: "admin"
        controller_password: "{{ eda_password }}"
        validate_certs: false
        name: "aap"
        description: "Example credential description"
        inputs:
          host: "{{ controller_hostname }}"
          username: "admin"
          password: "{{ controller_password }}"
        credential_type_name: "Red Hat Ansible Automation Platform"
        organization_name: Default

    - name: Create a Decision Environment
      ansible.eda.decision_environment:
        controller_host: "{{ eda_hostname }}"
        controller_username: "admin"
        controller_password: "{{ eda_password }}"
        validate_certs: false
        name: "eda-decision-env"
        image_url: "quay.io/kubealex/eda-decision-env"
        organization_name: Default

    - name: Create decision project
      ansible.eda.project:
        controller_host: "{{ eda_hostname }}"
        controller_username: "admin"
        controller_password: "{{ eda_password }}"
        validate_certs: false
        name: "cell-tower-remediation"
        organization: Default
        url: "{{ scm_url }}"
        scm_branch: master
        state: present

    - name: Create a Rulebook Activation
      ansible.eda.rulebook_activation:
        controller_host: "{{ eda_hostname }}"
        controller_username: "admin"
        controller_password: "{{ eda_password }}"
        validate_certs: false
        name: "cell-tower-remediation"
        project_name: "cell-tower-remediation"
        rulebook_name: "rulebook.yml"
        decision_environment_name: "eda-decision-env"
        credentials: "aap"
        organization_name: Default
      register: rulebook_result
      retries: 5
      delay: 10
      until: rulebook_result is not failed


